# Generated by Django 5.1.1 on 2024-10-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='history_pics/')),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('year_start', models.PositiveIntegerField()),
                ('year_end', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
